const products = [
{
    '_id': '1',
    'name': 'Bonsai de naranja',
    'image': '/images/uno.jpg',
    'description': 'Bonsai creado desde semilla',
    'clasification': 'Mame',
    'category': 'Bonsai',
    'price': '80.000',
    'countInStock': '1',
    'rating': '5',
    'numReviews': '1',
},
{
    '_id': '2',
    'name': 'Bonsai de Ciruelo Japonés',
    'image': '/images/dos.jpg',
    'description': 'Bonsai hecho a partir de un esqueje de un Bonsai de 10 años',
    'clasification': 'Mame',
    'category': 'Bonsai',
    'price': '80.000',
    'countInStock': '1',
    'rating': '4.5',
    'numReviews': '1',
},
{
    '_id': '3',
    'name': 'Mariposas y flores',
    'image': '/images/tres.jpg',
    'description': '',
    'type': 'Tejidos',
    'category': 'Crochet',
    'price': '65.000',
    'countInStock': '1',
    'rating': '4.5',
    'numReviews': '5',
},
{
    '_id': '4',
    'name': 'Margarita',
    'image': '/images/cuatro.jpg',
    'description': '',
    'type': 'Tejidos',
    'category': 'Crochet',
    'price': '12.500',
    'countInStock': '1',
    'rating': '4.8',
    'numReviews': '5',
},
{
    '_id': '5',
    'name': 'Flores en florero',
    'image': '/images/cinco.jpg',
    'description': '',
    'type': 'Tejidos',
    'category': 'Crochet',
    'price': '24.500',
    'countInStock': '1',
    'rating': '5',
    'numReviews': '5',
}

]

export default products